alias nb="vim ~/Dropbox/notes.txt"
alias projects="cd ~/projects"
alias vimrc="vim ~/.vimrc"
alias bashrc="vim ~/.bashrc"
alias red="redshift -l geoclue &"
alias lead="~/projects/lead/env/bin/python ~/projects/lead/lead.py"
